using Cardscape.Application.Saml;
using Cardscape.Domain.Common;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Wolverine;

namespace Cardscape.Api.Endpoints.Saml;

/// <summary>
/// SAML 2.0 SSO endpoints. The
/// <c>POST /saml/{workspaceSlug}/acs</c> endpoint is the
/// assertion consumer service; the
/// <c>GET /saml/{workspaceSlug}/login</c> endpoint kicks the
/// AuthnRequest. The metadata endpoint exposes the SP
/// metadata so the IdP can import it.
///
/// The auth pipeline is split: the IdP-facing
/// endpoints (login / acs / metadata) are unauthenticated
/// (the SAML flow itself is the authentication); the
/// admin endpoints (configure / get / disable) are
/// authenticated with the regular JWT.
/// </summary>
public static class SamlEndpoints
{
    public static IEndpointRouteBuilder MapSamlEndpoints(this IEndpointRouteBuilder app)
    {
        // IdP-facing (unauthenticated).
        var idp = app.MapGroup("/saml").WithTags("SAML");

        idp.MapGet("/{workspaceSlug}/login", (string workspaceSlug) =>
        {
            // The Sustainsys.Saml2 handler is registered
            // through the standard ASP.NET Core
            // challenge() flow; this endpoint is the entry
            // point the IdP redirects the user to.
            // The actual AuthnRequest is generated by
            // the configured Saml2AuthenticationHandler
            // when the request is challenged.
            return Results.Challenge(new Microsoft.AspNetCore.Authentication.AuthenticationProperties
            {
                RedirectUri = $"/saml/{workspaceSlug}/login-init"
            }, new[] { $"saml-{workspaceSlug}" });
        }).AllowAnonymous();

        idp.MapGet("/{workspaceSlug}/login-init", (string workspaceSlug) =>
        {
            // The second hop — the challenge handler
            // constructed the AuthnRequest and redirected
            // here. We forward to the Sustainsys default
            // ACS handler. A real implementation will wire
            // the Sustainsys Saml2 handler in
            // ServiceCollectionExtensions; this stub is
            // a 200 OK that explains the wiring shape so
            // operators can read the path before the
            // library is added.
            return Results.Ok(new
            {
                info = "SAML AuthnRequest initiated",
                workspaceSlug,
                next = $"POST /saml/{workspaceSlug}/acs (assertion consumer)"
            });
        }).AllowAnonymous();

        idp.MapPost("/{workspaceSlug}/acs", () =>
        {
            // Assertion consumer: the IdP POSTs the signed
            // SAMLResponse here. Sustainsys.Saml2
            // handles the request in the authentication
            // pipeline; this minimal endpoint is a 200
            // OK that operators can hit with curl to
            // confirm the route is mounted.
            return Results.Ok(new { info = "SAML ACS endpoint (assertion consumer service)" });
        }).AllowAnonymous();

        idp.MapGet("/{workspaceSlug}/metadata", (string workspaceSlug) =>
        {
            // SP metadata. The production handler is
            // generated by Sustainsys.Saml2.Metadata;
            // this stub returns a hand-written minimal
            // EntityDescriptor so the route exists.
            string entityId = $"https://cardscape.local/saml/{workspaceSlug}";
            string xml = $"""
                <EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" entityID="{entityId}">
                  <SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="true"
                                    protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
                    <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
                    <AssertionConsumerService index="0"
                                              Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                                              Location="https://cardscape.local/saml/{workspaceSlug}/acs" />
                  </SPSSODescriptor>
                </EntityDescriptor>
                """;
            return Results.File(System.Text.Encoding.UTF8.GetBytes(xml), "application/samlmetadata+xml");
        }).AllowAnonymous();

        // Admin (authenticated).
        var admin = app.MapGroup("/api/workspaces/{workspaceId:guid}/saml")
            .RequireAuthorization()
            .WithTags("SAML.Admin");

        admin.MapGet("/", async (Guid workspaceId, IMessageBus bus, CancellationToken ct) =>
        {
            var result = await bus.InvokeAsync<Result<SamlConnectionDto?>>(
                new GetSamlConnectionQuery(workspaceId), ct);
            return result.IsSuccess
                ? Results.Ok(result.Value)
                : MapError(result.Error);
        });

        admin.MapPost("/", async (
            Guid workspaceId,
            [FromBody] ConfigureSamlBody body,
            IMessageBus bus,
            CancellationToken ct) =>
        {
            var result = await bus.InvokeAsync<Result<SamlConnectionDto>>(
                new ConfigureSamlConnectionCommand(
                    workspaceId, body.Slug, body.DisplayName, body.IdpEntityId,
                    body.IdpMetadataUrl, body.IdpMetadataXml, body.SpEntityId),
                ct);
            return result.IsSuccess
                ? Results.Created($"/api/workspaces/{workspaceId}/saml", result.Value)
                : MapError(result.Error);
        });

        admin.MapDelete("/", async (Guid workspaceId, IMessageBus bus, CancellationToken ct) =>
        {
            var result = await bus.InvokeAsync<Result>(
                new DisableSamlConnectionCommand(workspaceId), ct);
            return result.IsSuccess ? Results.NoContent() : MapError(result.Error);
        });

        return app;
    }

    public sealed record ConfigureSamlBody(
        string Slug,
        string DisplayName,
        string IdpEntityId,
        string IdpMetadataUrl,
        string? IdpMetadataXml,
        string SpEntityId);

    private static IResult MapError(DomainError error) => error.Type switch
    {
        ErrorType.NotFound => Results.NotFound(new { error.Code, error.Message }),
        ErrorType.Forbidden => Results.Forbid(),
        ErrorType.Unauthenticated => Results.Unauthorized(),
        ErrorType.Conflict => Results.Conflict(new { error.Code, error.Message }),
        _ => Results.BadRequest(new { error.Code, error.Message })
    };
}
