using Cardscape.Domain.Common;

namespace Cardscape.Domain.Workspaces;

/// <summary>
/// A non-empty invitation token. The token is generated by the
/// Application layer (random base64url, 32 bytes), hashed with
/// SHA-256 at rest, and returned to the inviter in the clear
/// exactly once. The cleartext is delivered out-of-band (email
/// link); the server only ever sees the SHA-256 hash.
/// </summary>
public sealed record InvitationToken
{
    public const int CleartextByteLength = 32;
    public const int PrefixLength = 10;

    public string Hash { get; }

    private InvitationToken(string hash) => Hash = hash;

    public static InvitationToken FromHash(string hash) => new(hash);
}
