namespace Cardscape.Domain.Workspaces;

/// <summary>
/// Shape of an invitation token. The token is generated by the
/// infrastructure (random base64url, <see cref="CleartextByteLength"/>
/// bytes), hashed with SHA-256 at rest, and returned to the inviter in
/// the clear exactly once. The cleartext is delivered out-of-band (email
/// link); the server only ever sees the SHA-256 hash.
/// </summary>
public static class InvitationToken
{
    public const int CleartextByteLength = 32;
    public const int PrefixLength = 10;
}
