#!/usr/bin/env python
"""Reformat EF Core migration Designer files that have all content on
one line into properly formatted C# source. The `dotnet ef migrations
add` command on this project occasionally writes the Designer file
with spaces instead of newlines, which the `dotnet ef` tool does not
parse correctly. This script restores the LF line endings.
"""
import re

PATHS = [
    "src/Cardscape.Infrastructure/Persistence/Migrations/20260809121649_AddAttachments.Designer.cs",
    "src/Cardscape.Infrastructure/Persistence/Migrations/20260809123213_AddPasswordResets.Designer.cs",
]

for path in PATHS:
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()

    # Restore the leading comment + newlines.
    text = re.sub(r"//\s*<auto-generated\s*/>\s*", "// <auto-generated />\n", text, count=1)
    # Newline after every `using X;` statement.
    text = re.sub(r"(using\s+[^;]+;)\s*", r"\1\n", text)
    # `#nullable disable` directive on its own line.
    text = re.sub(r"\s*#nullable\s+(disable|enable|restore)\s*", r"\n#nullable \1\n", text)
    # `namespace X {` on its own line.
    text = re.sub(r"\s*namespace\s+", "\nnamespace ", text)
    # `[DbContext(...)]` and `[Migration(...)]` and `partial class` on separate lines.
    text = re.sub(r"\s*\[DbContext\(typeof\(([^)]+)\)\)\]\s*", r"\n    [DbContext(typeof(\1))]\n", text)
    text = re.sub(r"\s*\[Migration\(\"([^\"]+)\"\)\]\s*", r"\n    [Migration(\"\1\")]\n", text)
    text = re.sub(r"\s*partial\s+class\s+", "\n    partial class ", text)
    # `{` and `}` on their own lines.
    text = re.sub(r"\s*\{\s*", " {\n", text)
    text = re.sub(r"\s*\}", "\n}", text)
    # Newline before `///` so the doc comments land on their own line.
    text = re.sub(r"\s*///", "\n    ///", text)
    # Newline before `#pragma` directives.
    text = re.sub(r"\s*#pragma\s+", "\n#pragma ", text)
    # Collapse triple+ blank lines.
    text = re.sub(r"\n\n\n+", "\n\n", text)

    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"Reformatted: {path} (len={len(text)})")
